// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ultugtjnquhiwvidxaah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsdHVndGpucXVoaXd2aWR4YWFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNjg4NjAsImV4cCI6MjA2MDg0NDg2MH0.4H0CgfC0q_x4cumiPU7Rzdv6g5Ann6KCePShAeuYZcA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);